# -*- coding: utf-8 -*-
# Reformulation du camp attentiste : le nom et le mécanisme passent du registre
# de l'accusation à celui de l'argument tel que ses promoteurs le portent.
# L'analyse critique n'est pas supprimée : elle est déplacée dans « ancrage réel »
# et « ce qui peut le faire rater », où elle est sourcée et vérifiable.
ATT = {
"T01": ("Responsabilité individuelle","individualisation du problème",
  "Chacun décide de ses trajets, de son chauffage, de son assiette. Rendre ces choix visibles est plus rapide, moins coûteux et moins clivant qu'une contrainte imposée d'en haut.",
  "L'empreinte carbone individuelle a été popularisée par une campagne de BP en 2004. Les gestes individuels sans changement d'infrastructure plafonnent autour d'un quart de l'empreinte d'un ménage : l'essentiel dépend de choix collectifs. L'argument se retourne quand le soutien réel de la population est publié."),
"T02": ("Conditionner l'effort aux autres","whataboutisme",
  "Un bloc qui pèse 2 % des émissions mondiales ne change pas la trajectoire à lui seul. Demander que les gros émetteurs bougent d'abord est une exigence de réciprocité, pas un refus d'agir.",
  "L'argument est symétrique : si chacun attend l'autre, personne ne bouge. Il perd sa force face à un ajustement carbone aux frontières, qui rend l'effort conditionnel visible, et face au financement Nord-Sud, qui lève l'objection de capacité."),
"T04": ("Confiance dans l'innovation","optimisme technologique de report",
  "Le coût du solaire a baissé de 90 % en dix ans sans qu'on l'ait décrété. Engager aujourd'hui des sommes considérables dans des technologies qui seront obsolètes dans quinze ans est un mauvais calcul.",
  "L'argument vaut pour les technologies qui existent déjà et se déploient. Il devient un report quand il s'appuie sur des technologies non démontrées à l'échelle : fusion, captage direct dans l'air, hydrogène généralisé. Le budget carbone, lui, se dépense chaque année pendant l'attente."),
"T07": ("Engagement de long terme","objectif net zéro sans trajectoire",
  "Un objectif à trente ans donne aux entreprises la visibilité nécessaire pour investir, sans imposer de rupture brutale à une économie qui a besoin de temps pour s'adapter.",
  "Les engagements net zéro 2050 se sont généralisés sans que les trajectoires 2030 suivent. Un objectif sans étape intermédiaire n'engage aucun décideur en exercice. Une institution indépendante de suivi transforme l'annonce en dette publiquement mesurée chaque année."),
"T08": ("Défense des ménages modestes","instrumentalisation sociale",
  "Une taxe sur l'énergie frappe proportionnellement plus fort les bas revenus, les ruraux et ceux qui n'ont pas le choix de leur mode de chauffage ou de transport. L'objection est fondée.",
  "Elle est fondée tant que rien n'est rendu. Le dividende carbone canadien rend davantage aux ménages modestes qu'il ne leur coûte, et n'a jamais été renversé. Face à une redistribution visible, l'argument perd les deux tiers de sa force."),
"T09": ("Défense du mode de vie","défense identitaire du statu quo",
  "La voiture, la viande, le départ en vacances ne sont pas des caprices : ce sont les marqueurs d'une vie normale que des générations ont mis un siècle à conquérir. Les remettre en cause a un coût politique réel.",
  "L'argument attaque le soutien de fond, pas seulement la perception — c'est ce qui le rend redoutable. Il s'affaiblit face à un récit de gain plutôt que de privation, à condition que ce récit précède l'attaque et que les mesures effectivement prises ne le démentent pas."),
"T11": ("Réalisme sur les délais","fatalisme démobilisateur",
  "Regarder les chiffres en face : le budget 1,5 °C est presque épuisé, les émissions mondiales n'ont pas encore baissé. Promettre l'inverse entretient une illusion qui se paiera en désillusion.",
  "Le constat est exact, la conclusion ne l'est pas : chaque dixième de degré évité compte, et la trajectoire mondiale est passée de 3,6 °C à 2,6 °C entre 2015 et 2025. Le levier se renforce mécaniquement quand la partie se dégrade — c'est pourquoi montrer ce qui a marché est le seul contre efficace."),
"T13": ("Représentation d'intérêts","lobbying d'obstruction",
  "Les secteurs concernés connaissent leurs contraintes techniques mieux que le législateur. Intervenir dans l'écriture du texte, avant le vote, évite des normes inapplicables.",
  "InfluenceMap documente plusieurs centaines de millions de dollars par an d'influence climatique obstructive, avec un rapport coût/effet sans équivalent. Les registres de transparence et le reporting obligatoire en réduisent le rendement sans le supprimer."),
"T17": ("Allègement du contrôle","capture de l'agence réglementaire",
  "Une autorité de contrôle surdimensionnée coûte cher et ralentit les projets. Recentrer ses moyens sur ses missions essentielles est une bonne gestion des finances publiques.",
  "Le résultat est que la norme reste au Journal officiel et cesse d'être appliquée. C'est moins visible qu'une abrogation, donc moins coûteux politiquement. Une loi-cadre avec budget carbone opposable rend le sous-contrôle attaquable en justice."),
"T19": ("Harmonisation nationale","préemption législative",
  "Un patchwork de règles locales fragmente le marché intérieur et crée une insécurité juridique pour les entreprises. Fixer la règle au niveau national est un principe d'égalité devant la loi.",
  "Plus de vingt États américains interdisent depuis 2020 à leurs villes de bannir le gaz. L'harmonisation retire l'échelon où les majorités climatiques sont les plus solides. Les réseaux de villes internationaux contournent partiellement le blocage."),
"T20": ("Simplification normative","détricotage administratif",
  "Alléger des obligations de reporting devenues illisibles rend du temps et de l'argent aux entreprises, en particulier aux plus petites. Personne ne défend la complexité pour elle-même.",
  "Le paquet omnibus européen de 2025 a fortement réduit le périmètre de CSRD et CSDDD. Vider une norme par simplification ne mobilise personne, contrairement à une abrogation. Inopérant contre une mesure inscrite dans une trajectoire opposable."),
"T21": ("Concertation approfondie","obstruction procédurale",
  "Une réglementation mal préparée se fait annuler et fait perdre des années. Prendre le temps de la consultation et de l'étude d'impact est la condition de sa solidité juridique.",
  "L'argument ne s'oppose jamais publiquement au fond — c'est ce qui le rend difficile à combattre. Multiplier les phases repousse l'entrée en vigueur sans qu'aucun vote défavorable n'ait lieu. Des échéances datées dans la loi rendent le report juridiquement attaquable."),
"T22": ("Adaptation sectorielle","exemption négociée",
  "Certains secteurs n'ont pas d'alternative technique disponible. Les soumettre à la règle générale ne réduit rien et détruit de la valeur : l'exception est une mesure de bon sens.",
  "L'aviation et le maritime sont restés longtemps hors ETS, les dérogations agricoles ont été obtenues en 2024. Chaque exemption affaiblit la crédibilité du texte et en appelle d'autres. Sans effet sur un bloc verrouillé par une loi-cadre."),
"T23": ("Clause de réexamen","annulation programmée",
  "Une trajectoire fixée pour dix ans doit pouvoir être ajustée si la technologie ou le contexte économique changent. Prévoir un rendez-vous est de la bonne législation.",
  "Insérer une révision datée coûte presque rien au moment du vote et rouvre tout au moment choisi. Le règlement européen de fin du thermique en 2035 comporte une clause de réexamen en 2026. Un accord transpartisan retire la revoyure du jeu politique ordinaire."),
"T24": ("Protection des investissements","arbitrage investisseur-État",
  "Un investisseur qui a engagé des milliards sur la foi d'un cadre juridique doit pouvoir être indemnisé si l'État change ce cadre. C'est le principe de sécurité juridique.",
  "RWE et Uniper ont réclamé environ 1,4 Md€ aux Pays-Bas, Rockhopper 190 M€ à l'Italie, via le Traité sur la Charte de l'énergie. L'effet dissuasif dépasse largement les cas jugés. Les retraits du Traité depuis 2023 réduisent le terrain de jeu."),
"T25": ("Recours en légalité","contentieux dilatoire",
  "Une norme entachée d'un vice de procédure ou disproportionnée doit pouvoir être contestée. Le recours est un droit, pas une manœuvre.",
  "Gagner n'est pas nécessaire : trois à cinq ans de suspension suffisent. Les réglementations environnementales fédérales américaines font l'objet de recours quasi systématiques. Sans effet sur les mesures adossées à une obligation juridictionnelle supérieure."),
"T26": ("Action en diffamation","procédure-bâillon",
  "Une accusation publique infondée cause un préjudice réel. Saisir le juge est la voie normale pour le faire constater.",
  "Le déséquilibre de moyens fait l'effet : une ONG ou un journaliste indépendant s'épuise financièrement avant le jugement, quelle que soit l'issue. La directive européenne anti-SLAPP de 2024 rend la procédure risquée pour son auteur dans les blocs européens."),
"T31": ("Communication sur les engagements","greenwashing",
  "Une entreprise qui investit dans la transition a le droit de le faire savoir. La communication est aussi ce qui rend la transition désirable auprès du public.",
  "Les campagnes des majors portent souvent sur des investissements bas carbone inférieurs à 5 % de leurs dépenses d'investissement. L'effet sur l'opinion est le sentiment que le problème est déjà traité. Vulnérable au contentieux publicitaire et à l'interdiction de publicité fossile."),
"T33": ("Investissement dans les médias","concentration médiatique",
  "La presse perd de l'argent. Des actionnaires qui la recapitalisent la maintiennent en vie ; l'indépendance des rédactions est garantie par leur statut.",
  "C'est le seul levier vraiment cumulatif du camp : il convertit du capital en influence durable sur l'attention. Cher, lent et très visible, il expose à l'investigation et au débat public sur la concentration."),
"T36": ("Maîtrise du calendrier","saturation de l'attention",
  "Communiquer au bon moment fait partie du métier. Publier un rapport technique en pleine actualité chargée n'est pas une faute, c'est un arbitrage.",
  "La pratique est documentée : les publications défavorables sortent les veilles de week-end et de grands événements. Une équipe d'attribution rapide publie avant la fenêtre de saturation."),
"T38": ("Bataille des valeurs","polarisation identitaire",
  "L'écologie porte un projet de société qui ne dit pas son nom. Le nommer et le contester ouvertement est un débat démocratique légitime.",
  "La polarisation partisane du climat est mesurée dans plusieurs démocraties depuis 2010. Une fois installée, elle ferme durablement la voie de l'accord transpartisan — y compris pour son auteur, qui perd aussi la possibilité du compromis."),
"T39": ("Défense du pouvoir d'achat","instrumentalisation du coût de la vie",
  "Une hausse du prix de l'énergie tombe immédiatement sur des ménages sans marge. Le rappeler au moment où la facture arrive n'est pas de la manipulation, c'est de la représentation.",
  "C'est le levier numéro un du camp depuis la crise énergétique de 2022, et il a suffi à retourner le discours européen sur le Pacte vert. Il perd la moitié de sa force face à une compensation visible, davantage encore face à une coalition qui inclut le pouvoir d'achat dès le départ."),
"T40": ("Sécurité d'approvisionnement","instrumentalisation de la crise énergétique",
  "Un pays qui ne peut plus se chauffer ni produire n'a plus de politique climatique du tout. Sécuriser l'approvisionnement est un préalable, pas une alternative.",
  "La peur de la coupure a autorisé en quelques semaines, après 2022, ce qu'aucun débat n'aurait accordé en dix ans : terminaux GNL, réouvertures de centrales. Le renforcement du réseau et du stockage retire l'argument de la fragilité."),
"T41": ("Écoute des territoires","fracturation de la coalition",
  "Agriculteurs, automobilistes, ruraux, salariés d'un site industriel : ces gens subissent la transition sans l'avoir décidée. Porter leur voix est le rôle d'un représentant.",
  "Détacher un groupe social coûte beaucoup moins cher que convaincre l'ensemble de la population — les mobilisations agricoles de 2024 et les Gilets jaunes de 2018 l'ont montré. Une coalition construite dès le départ sur l'emploi et le pouvoir d'achat offre peu de prise."),
"T43": ("Investissement d'infrastructure","verrouillage carbone",
  "Un terminal, un gazoduc, une centrale se décident sur quarante ans. Sécuriser l'approvisionnement d'une région relève de la responsabilité élémentaire d'un État.",
  "C'est le principal irréversible du camp : ce qui est coulé engage des décennies, quelles que soient les alternances. Le retrait des assureurs et des financeurs est le seul levier qui bloque un projet avant la coulée."),
"T44": ("Contrat d'approvisionnement de long terme","verrouillage contractuel",
  "Un acheteur obtient un prix stable, un vendeur sécurise son investissement. C'est le fonctionnement normal d'un marché de matières premières.",
  "Le droit privé verrouille ce que la réglementation ne peut plus atteindre : rompre coûte plus cher qu'exécuter. Les contrats GNL de vingt à vingt-cinq ans signés depuis 2022 courent au-delà des objectifs climatiques européens. Une date butoir annoncée très tôt dissuade la signature."),
"T45": ("Alerte sur l'emploi industriel","chantage à la délocalisation",
  "Un site qui ferme ne rouvre pas, et sa production repart là où la règle est plus souple — sans gain climatique. Le signaler avant la décision est une alerte, pas une menace.",
  "L'argument est efficace en période électorale et souvent invoqué sans que la fermeture suive. L'ajustement carbone aux frontières supprime l'avantage du moins-disant et donc le fondement de l'alerte."),
"T50": ("Optimisation des aides publiques","capture de la subvention",
  "Une aide publique existe pour être utilisée. Une entreprise qui la mobilise dans les règles fait son travail ; c'est au dispositif de fixer ses conditions.",
  "Le levier retourne la politique industrielle adverse contre son émetteur : l'argent est encaissé, la trajectoire ne bouge pas. Une institution indépendante de suivi rend l'écart visible dès le rapport suivant."),
"T51": ("Neutralité par compensation","compensation au lieu de réduction",
  "Une tonne évitée ailleurs vaut climatiquement une tonne évitée ici, et coûte souvent dix fois moins. Financer la réduction là où elle est la moins chère est rationnel.",
  "L'équivalence suppose que la réduction ait réellement lieu et soit additionnelle, ce que la majorité des projets examinés ne démontre pas. Le marché volontaire a perdu plus de 60 % de sa valeur depuis 2022. Le reporting obligatoire distingue réduction réelle et crédit acheté."),
"T52": ("Neutralité technologique","exemption technologique",
  "Le législateur fixe l'objectif, pas la solution technique. Interdire une technologie plutôt que des émissions, c'est faire un pari industriel à la place du marché.",
  "L'exemption e-fuels obtenue en 2023 sur le règlement européen de fin du thermique porte sur une filière dont le coût et le rendement restent prohibitifs à l'échelle. Le principe est défendable, son usage ici vide le texte. Sans effet sur un bloc verrouillé."),
"T05": ("Le gaz comme énergie de transition","verrouillage gazier",
  "Le gaz émet à la combustion moitié moins que le charbon et fournit l'équilibrage dont un réseau très renouvelable a besoin. Substituer le gaz au charbon est un gain immédiat.",
  "Le gain à la combustion est réel ; les fuites de méthane en amont en annulent une part importante, et l'infrastructure construite engage quarante ans. Le classement du gaz dans la taxonomie verte européenne date de 2022. Le renforcement du réseau et du stockage supprime l'argument de l'équilibrage."),
}
